# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='top',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
