# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_item_icon'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spellacquired',
            unique_together=set([('character', 'spell')]),
        ),
    ]
