# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('health', models.PositiveIntegerField(default=100, max_length=16)),
                ('xp', models.PositiveIntegerField(blank=True, default=0, max_length=16, verbose_name=b'Current XP')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_currently_equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level_required', models.PositiveIntegerField(max_length=100)),
                ('worth', models.DecimalField(decimal_places=2, max_digits=100)),
                ('spaces', models.PositiveIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'items')),
                ('worth', models.DecimalField(decimal_places=2, max_digits=100)),
                ('level_required', models.PositiveIntegerField(max_length=200)),
                ('damage', models.PositiveIntegerField(default=0, max_length=200, null=True)),
                ('healing', models.PositiveIntegerField(default=0, max_length=200, null=True)),
                ('armor', models.PositiveIntegerField(default=0, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='for_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Group'),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='inv_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.InvBag'),
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Type'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='characteritem',
            unique_together=set([('item', 'is_currently_equipped')]),
        ),
    ]
