# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name=b'Current XP'),
        ),
        migrations.AlterField(
            model_name='invbag',
            name='level_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invbag',
            name='spaces',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='armor',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='healing',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='level_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.ManyToManyField(default=None, to='characters.Position'),
        ),
    ]
