# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20160322_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteritem',
            unique_together=set([('item',)]),
        ),
    ]
