# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20160322_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteritem',
            name='is_currently_equipped',
        ),
    ]
