# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_characteritem_is_currently_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='equipped_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Position'),
        ),
        migrations.AlterUniqueTogether(
            name='characteritem',
            unique_together=set([('item', 'equipped_to')]),
        ),
    ]
