# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_item_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='for_class',
        ),
    ]
