# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20160325_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='_Class',
        ),
    ]
