# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_dealt', models.PositiveIntegerField(max_length=200, null=True)),
                ('damage_taken', models.PositiveIntegerField(max_length=200, null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_health', models.PositiveIntegerField(blank=True, max_length=16, verbose_name=b'Current Character Health')),
                ('enemy_health', models.PositiveIntegerField(blank=True, max_length=16, verbose_name=b'Current Enemy Health')),
                ('resource', models.PositiveIntegerField(default=1, max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemies.Enemy')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(null=True)),
                ('damage', models.PositiveIntegerField(max_length=15)),
                ('level_required', models.PositiveIntegerField(max_length=15, null=True)),
                ('turn_cooldown', models.PositiveIntegerField(max_length=200)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Type')),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='enemy_return_spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliation', to='match.Spell'),
        ),
        migrations.AddField(
            model_name='attack',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
        migrations.AddField(
            model_name='attack',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Spell'),
        ),
    ]
