# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20160322_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='type',
        ),
        migrations.AlterField(
            model_name='attack',
            name='enemy_return_spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliation', to='spells.Spell'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell'),
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
    ]
