# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('enemies', '0001_initial'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_dealt', models.PositiveIntegerField(null=True)),
                ('damage_taken', models.PositiveIntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('enemy_return_spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliation', to='spells.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_health', models.PositiveIntegerField(blank=True, verbose_name=b'Current Character Health')),
                ('enemy_health', models.PositiveIntegerField(blank=True, verbose_name=b'Current Enemy Health')),
                ('resource', models.PositiveIntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemies.Enemy')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
        migrations.AddField(
            model_name='attack',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.Spell'),
        ),
    ]
